### ISSUE TITLE
v2.4.3 7zip file raises a thread in Windows Defender on Windows 10

### ISSUE THREAD

**Issue by ramonsmits** [White-Tiger/T-Clock#100]
v2.4.3 7zip file raises a thread in Windows Defender on Windows 10 but the regular zip file does not give a thread warning.

**Comment by White-Tiger** [comment]
well... thanks for informing me but what do you think I could do about it?
Both MSVC archives *(the ones without `_static`)* are zipped with the very same files inside.. And both are zipped by the same 7zip 16.04 from an AppVeyor build machine... So if one got a virus, both actually have it ;)

Though, if you ask Virustotal, both are actually clean.

**Comment by rkelis** [comment]
just for information, _static version gave this:

Trojan: Win32/Spursint.F!cl 
 
 
  
Also detected as: 
•	Severe 
 
Trojan:Win32/Spursint.F!cl
Alert level: Severe
First published: Sep 12, 2016

**Comment by rocboozer** [comment]
I downloaded and am running the 7zip file.  Do I have a virus??
