### ISSUE TITLE
2.4.3 beta - "turn off monitor" feature flickers many times

### ISSUE THREAD

**Issue by captainhook** [White-Tiger/T-Clock#101]
Steps:
1. Enable feature
2. Lock workstation
3. Wait 5 seconds for screen to turn off
4. Wake screen with mouse movement
5. Wait another 5 seconds for screen to turn off
6. Wake screen again with mouse movement

This causes the screen to turn on and off continuously (20+ times). It stops after a while, however the period differs each time.

This could very well be driver specific? I'm not sure. However some testing from the community would help us figure out what's causing it.
I have a 970M, and a i7-6700HQ, latest drivers. Windows 10.

**Comment by White-Tiger** [comment]
well... your windows is of more interest here...
anyway, so it works as expected in the beginning, but bugs out after a while?

**Comment by captainhook** [comment]
Sorry, forgot to mention it's on Windows 10.
But yes, it works fine on the first round, but if I let it timeout a second time then that is when the bug begins to occur.

**Comment by White-Tiger** [comment]
which doesn't occur on my end... It always happens after your 2nd "wake"?

I bet you've got a 64bit Windows 10... but I'll better ask anyway :P Do you?
How did you attach your monitor? HDMI, DVI, DP?
How fast is your monitor turning off/on? _(mine takes a while... like almost 5 seconds)_

**Comment by captainhook** [comment]
Yes, 64bit Windows 10 :D
It is a laptop, Dell XPS, and the screen turn on/off period is about 1 second

**Comment by White-Tiger** [comment]
aye captain!
But I still can't reproduce that... do you have any other PC you can try this with?

And sorry about asking how you've attached your monitor although you've already mentioned your laptop.. _(GTX 970M)_

**Comment by White-Tiger** [comment]
after step 6 (when the screen is turned on and off continuously), do you keep moving your mouse or leave it idle again? Basically, does it keep turning off even though you're not "idle"?
(I assume this is what happens, but I want to be sure)

**Comment by White-Tiger** [comment]
I've done a new release, https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc
can you try it out and see if that fixes anything?

If it's fixed.. it seems like you've got some slow responding apps running *(part of the issue, still T-Clock's fault)*
