### ISSUE TITLE
T-Clock started on startup not showing calendar or menu in Win8

### ISSUE THREAD

**Issue by DiThi** [White-Tiger/T-Clock#11]
In Windows 8, T-Clock x64 2.4.0 build 351, configured to run at startup (it added itself to the Startup menu), no click has effect (it doesn't show windows native calendar, no menu) until application is run again at any point after startup.

**Comment by White-Tiger** [comment]
but the clock itself is visible?
can you provide a detailed description on how you "fix" it for you? Just starting T-Clock while it's already running, killing it via taskmanager etc.?

**Comment by DiThi** [comment]
The clock is visible. It's just that it doesn't respond to clicks. It works after I just start T-Clock again while it's already running, no killing.

I suspect there's some kind of race condition where it's started before the taskbar has initialized.

**Comment by White-Tiger** [comment]
theres one last think you'll have to check. When it happens again, can you look if there's a "Clock(64).exe" process running?

The *"It works after I just start T-Clock again while it's already running, no killing"* is quite important here, as T-Clock doesn't do that much if started a 2nd time..

**Comment by White-Tiger** [comment]
any news on this?

**Comment by DiThi** [comment]
It hasn't happened again. I don't know if it fixed itself or what. I very rarely reboot anyway.

**Comment by White-Tiger** [comment]
did you use the static build?

**Comment by White-Tiger** [comment]
I'll close this for now, reopen if it occurs again.
