### ISSUE TITLE
Wrong number of week of year

### ISSUE THREAD

**Issue by DJHeady** [White-Tiger/T-Clock#117]
Hello,

In my T-Clock I have wrong number of week number. See screenshot. Maybe a bug?

[https://www.dropbox.com/s/2ajnjazhyef07u6/2017-10-05%2013_56_08-New%20Issue%20%C2%B7%20White-Tiger_T-Clock.png](https://www.dropbox.com/s/2ajnjazhyef07u6/2017-10-05%2013_56_08-New%20Issue%20%C2%B7%20White-Tiger_T-Clock.png)

**Comment by White-Tiger** [comment]
Does non of the "First week of year" settings work for you? Well, week numbering is handled by Windows...

**Comment by DJHeady** [comment]
Damn, it worked! So solved. I had selected an US setting instead of EU setting (since Im in the EU). But that means that US and EU have different week numbers the whole of this year. That is strange...and crazy...
