### ISSUE TITLE
Sunday shown as "0" i.s.o. "7" even though "wi" used

### ISSUE THREAD

**Issue by QuintS** [White-Tiger/T-Clock#120]
- Custom format: dde - wkyyWWi.wi\ndd-mm-yyyy - HH:nn
- First week with four days (EU)
- First day of week: Monday (Has no influence on custom format date shown with format as above as "wi" via ISO...)

Shows up today as:
Sun - wk1744.0
05-11-2017 - 17:56

**Comment by White-Tiger** [comment]
well, you're right ;)
My implementation was flawed in this regard... seems like I've moved [this](../blob/master/src/DLL/format.c#L349) around. The increment should happen after the `if`

Do you compile T-Clock yourself or do you need a new build?

**Comment by QuintS** [comment]
No worries, thanks for your response!

**Comment by White-Tiger** [comment]
Well, now I'm confused xD So does that mean you're not needing it ASAP?
If it's inconvenient for you to have this bug, I wouldn't mind creating a new release...

**Comment by QuintS** [comment]
Haha, sorry, it's something I wanted to give feedback on not requiring a whole new release. So you could roll it up into the next release. As for me and the ASAP part, well, mostly work of a linux based PC at home, so shouldn't encounter this during regular office hours :).

**Comment by White-Tiger** [comment]
Now implemented in [v2.4.4](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc)
