### ISSUE TITLE
Scrolling in Calendar stops working

### ISSUE THREAD

**Issue by bugmenot30701** [White-Tiger/T-Clock#124]
Opening the TClock Calendar allows you to scroll to future days or months using the right arrow & Page Down keys.  However, when you leave the Calendar window open, click on a different window to give it focus, then click back on the Calendar window, the right arrow & Page Down keys no longer work.

Thanks for an excellent utility!  I've been using TClock for years, and very much like having the ability to customize the look & feel of the system clock.  Thanks for your continued support of this great tool !

**Comment by White-Tiger** [comment]
well.. you've actually reported that in #69 and never responded to my question...
