### ISSUE TITLE
Week displayed in context bubble does not match calendar week

### ISSUE THREAD

**Issue by tbird1965** [White-Tiger/T-Clock#129]
I just noticed today that when I hover over the T-Clock, the bubble tells me it is week 1 (should be week 2) - yet the calendar shows today as part of week 2.  I have found nothing in settings that affects the week shown in the context bubble.  Am I missing a setting?

I am running Windows 7 and T-Clock Redux x64 - 2.4.3 build 471 (just updated)

![image](https://user-images.githubusercontent.com/20564407/34675945-1f037464-f459-11e7-9573-d1098cb65477.png)

![image](https://user-images.githubusercontent.com/20564407/34675961-2b812e48-f459-11e7-9fbd-d897b13931a2.png)

**Comment by White-Tiger** [comment]
duplicate of #128
