### ISSUE TITLE
build 3.6.9 doesn't start

### ISSUE THREAD

**Issue by MielsvS** [White-Tiger/T-Clock#13]
I was running 2.4.0 build 351 just fine, just updated to build 3.6.9 (to fix the copy to clipboard issue). Now the application won't start anymore. When starting clock64.exe three instances of the processes do appear in ProcessExplorer, but the tray icon doesn't appear:

![clock64 processes](https://cloud.githubusercontent.com/assets/15874425/11187786/1b701d06-8c88-11e5-9a68-566a636fbb22.png)

I can't kill the instances either:

CMD as Admin;
taskkill /f /im clock64.exe
ERROR: The process "Clock64.exe" with PID 9472 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "Clock64.exe" with PID 9468 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "Clock64.exe" with PID 4600 could not be terminated.
Reason: There is no running instance of the task.

I'm running Windows 10 Pro x64, I am admin.

clock.exe has exactly the same behaviour.
I can still run the previous build of T-Clock. I have to reboot to get rid of the unresponsive processes of the latest build.

**Comment by MielsvS** [comment]
Your remark "suspicious" (and your offer to try to reproduce :)) made me investigate further:

booted into safe mode (minimal): no problem at all
regular reboot, closed al tray icons: no probem at all
anti virus was my next item on the checklist. Another reboot, only disabled anti virus: no problem
activated antivirus: problem was there again.
I was running Avast:
program: 10.4.2233  of sept 17th 2015 15:12:58
definitions: 151116-1 of november 16th 20:43:26
I upgraded both. Definitions where up to date, program updated to 11.1.2241

This solved the problem. I didn't have to add any files to a whitelist or something.

Thanks for your time (and program)!

**Comment by White-Tiger** [comment]
which build were you using though? The static or non-static?

**Comment by MielsvS** [comment]
The non-static
(to be certain the problem wasn't in the zip I tried the .7z and .zip version, but no difference between the two).
