### ISSUE TITLE
Play a sound on Recycle Bin cleared

### ISSUE THREAD

**Issue by Rictusempra** [White-Tiger/T-Clock#130]

**Comment by White-Tiger** [comment]
I'm sorry to say that.. but it does that already. _(or at least it should, if not, report back)_
I assume you're on Windows 10 though.. which disabled this sound by default.. so you'll have to enable it first:

Windows Settings -> Personalization -> Themes -> Sounds,
scroll down to `File Explorer` _(which is near the end of the list)_ and set a sound file for `Empty Recycle Bin` such as `Windows Recycle.wav`
