### ISSUE TITLE
Post to Microsoft Store

### ISSUE THREAD

**Issue by Rictusempra** [White-Tiger/T-Clock#138]
An easy way for your to push updates

**Comment by White-Tiger** [comment]
well.. isn't that only for Modern UI apps? T-Clock relies heavily on the Win32 API

**Comment by Rictusempra** [comment]
You can also bridge win32 APIs into it.

**Comment by White-Tiger** [comment]
I'll close this as it seems to be an impossible task _(like I thought)_
___
> “Apps that require elevation for any part of their functionality won't be accepted in the Microsoft Store.”

_(time sync, or other system "impacting" functions...)_

> “Your app requires a kernel-mode driver or a Windows service.”

_(yet again for time sync that doesn't ask user for elevation.)_

> “Your app's modules are loaded in-process to processes that are not in your Windows app package.”

_(basically everything; T-Clock core function: the clock)_

> “Your app modifies the HKEY_LOCAL_MACHINE (HKLM) registry hive.”

_(rarely needed, actually only used in the past)_

> “Your app is linking C runtime libraries (CRT) in an unsupported manner.”

_(everything compiled by GCC might be affected... maybe an anti-GCC rule?)_

> “Your app starts a utility to perform tasks.”

_(some time options & menu entries, might not be compatible with Windows S)_

**Comment by nickpassaro** [comment]
I don't know what the situation was with MSIX when this issue was closed, but since that's the new way forward with bringing Win32 apps to the store, could this issue be reopened and investigated?
