### ISSUE TITLE
Calender opens at the lower-CENTER of the screen

### ISSUE THREAD

**Issue by MortenKabel** [White-Tiger/T-Clock#14]
After upgrading to T-Clock x64 2.4.0 build 369 on Windows 7, the (12 month) calendar is now opening at the lower-CENTER of my screen (2560x1440) instead of lower-right corner.

**Comment by White-Tiger** [comment]
I'm aware of this issue and a fix is scheduled for Friday. Unless you consider it to be really important^^

**Comment by MortenKabel** [comment]
Thank you for a great job!!!!

**Comment by White-Tiger** [comment]
fixed in latest release, though I couldn't provide a static build this time...
