### ISSUE TITLE
T-Clock hangs on Window 10 Build 17115.rs4

### ISSUE THREAD

**Issue by StartledLemon** [White-Tiger/T-Clock#142]
Hello,

I installed T-Clock v2.4.4.497 earlier today on my laptop which was running Windows 10 Pro Build 17101.rs4. T-Clock was running smoothly - I adjusted the options to display the date & time over 2 lines just as I wanted.

I then updated to Windows 10 Pro Build 17115.rs4 and on restarting Windows after the update I noticed the following:

• There's a 'Clock64.exe' process running but my taskbar's clock is showing as the usual format (i.e., T-Clock's configuration of the date & time is not showing)
• The Clock64.exe process is using 15-20% CPU
• Left or right-clicking the taskbar clock no longer shows the calender or T-Clock menu
• Double-clicking the 'Options.exe' executable in the 'misc' directory in T-Clock's installation folder results in a window appearing (flashes) momentarily on screen but no options window appears

Is there a known workaround for these issues?

Kind regards,

/Neil

**Comment by White-Tiger** [comment]
hmm... I've tested it with the rs4 Insider build, and it's working for me... I assume it's always like that for you? Even after multiple restarts?

**Comment by StartledLemon** [comment]
Hello,

Well, it was still an issue after several restarts, but out of curiosity I ran the ".reset_portable.cmd" script in the T-Clock installation directory and everything came back to life - T-Clock is now running happily.

Thanks for responding!

Kind regards,

/Neil

**Comment by White-Tiger** [comment]
hmm... were you using the "portable" mode before? _(always using the T-Clock.ini config file)_
I'm happy for you that you've got it working, but since the "faulty" settings are gone there's no way for me to fix the issue... so it could happen again...

Anyway, do you have just one monitor or how many do you use?

**P.S.** Options.exe is still just a dummy, so the options didn't move there yet.

**Comment by StartledLemon** [comment]
No - I wasn't using "portable" mode. The T-Clock.ini file was only created when I ran the ".reset_portable.cmd" script.

I have dual monitors! Oddly enough, even with the "Duplicate clock on each additional taskbar" checked in T-Clock Options the clock only appears on the left-hand monitor (i.e., monitor 1).

**Comment by White-Tiger** [comment]
so... if you close T-Clock, rename `T-Clock.ini` and launch it again, it'll stuck once again?
If so, it would help to get an export of your settings. Eg. by following these steps:
- download helper scripts: [import-export.zip](https://github.com/White-Tiger/T-Clock/files/1809060/import-export.zip)
- extract somewhere _(as long as you can write to that folder... eg. Desktop, Downloads folder etc.)_
- run `_export.cmd` _(and maybe then adjust exported .reg file(s) if there's any sensible / private stuff in it)_
- mail those exported .reg file(s) to T-Clock@WhiteTiger.e4ward.com (if possible, don't reset your settings yet... don't run `_reset-settings.reg` not even `_import.cmd`)

you may rename your `T-Clock.ini` afterwards and keep using that for the time being.

It's also weird that `Duplicate clock on each additional taskbar` seems to have no effect... it should have... Though, there are reports about it crashing Explorer.exe

**Comment by StartledLemon** [comment]
Apologies for the delayed response - I've been away from this particular laptop for a week or so.

As requested, I closed T-Clock and renamed the .ini file and launched it again (by double-clicking the Clock64.exe executable). There is now a Clock64 process running but I do not see the expected changes to the clock in the taskbar. I've therefore run the _export.cmd script to generate the _export.reg file which I've just emailed to you separately.

I'm having varying results with using the "Duplicate clock on each additional taskbar" option. Sometimes there's no clock at all on the additional taskbar, sometimes there is but it's displaced ~60 pixels to the left (it's as if the 'Notifications' icon visible on the primary monitor is there, but invisible on the secondary monitor), and sometimes T-Clock appears just fine on the secondary monitor.

**Comment by White-Tiger** [comment]
Thanks for the export file, I'm fully able to reproduce the issue now.

About your additional taskbars... did that behavior start recently or for as long as you can remember?
Windows 10 forced me to do a lot of changes to the way the Clock shows itself.. so it's possible that it's a regression... though I only noticed an issue on Windows 2000 that caused excess spacing (primary Clock though)

**Comment by White-Tiger** [comment]
Thanks for the export file, I'm fully able to reproduce the issue now. _(so you may now play with your settings as you please, or keep using the portable mode / .ini)_

About your additional taskbars... did that behavior start recently or for as long as you can remember?
Windows 10 forced me to do a lot of changes to the way the Clock shows itself.. so it's possible that it's a regression... though I only noticed an issue on Windows 2000 that caused excess spacing (primary Clock though)

**Comment by m4gnify** [comment]
Hey!

Thought I'd chip in, since I have the same issue with dual monitors (Win 10.)

First start of t-clock worked perfectly, it appeared on both monitors taskbars without any problems.
A few days later when I restarted my PC (I don't do that very often), explorer stopped working as soon as t-clock tried to hook into the taskbar.
After a few tries (launching Clock64.exe), t-clocks settings window opened, and though it was hanging and stopped working a few times, i was able to turn off the dual monitor support, and now it works just fine, though only on my primary monitor (which luckily is where I want it to be :))
I don't know if the portable mode helped (though I activated it.)

Anyway, I love this app, and thank you for your work!

**Comment by White-Tiger** [comment]
hmm.. did you reply to the wrong issue?
Yours is a multi-monitor issue since you've fixed it by disabling it... also, yours is crashing the Explorer.

This issue is about T-Clock hanging and consuming CPU for no good reason but nothing crashes...

**Comment by m4gnify** [comment]
Probably, I didn't look that much in the issues page. Found this while googling.
Sorry
