### ISSUE TITLE
Suggestions / Feature Requests

### ISSUE THREAD

**Issue by gaveitatry** [White-Tiger/T-Clock#147]
I have two suggestions or feature requests.

1.) I am currently using a format that causes the result to look like this:
Sat, 04/28/18 @ 3:55 AM
That's fine, but I would be much happier if I could change the format of the day of week text so that it is all capitalized, like this.
SAT, 04/28/18 @ 3:55 AM

2.) Another thing that would be great is if I could have text size options for each line.
So, let's say that I have two lines and it looks like this:
Sat, 04/28/18
3:55 AM
It would be nice if I could use a different text options for Line 1 and an even different text options for Line 2.  That way both lines won't be the same exact height.  This is important because the TIME is the thing that I first want to notice.  But then it would be cool if I could see smaller text above the TIME that shows other information such as day of week and today's date.  If the day of week and today's date were smaller, then I could spot the time easier but still have all information easily available.  I think that this could be accomplished by having "Text Options" for two lines.  Line 1 and Line 2.  I think that three lines might be a bit much because I am using small icons and I can't fit three lines without making the text super small.  Some people use big icons, so maybe they could benefit from text options for a Line 3, but I still find it doubtful.  It's up to you.

Thank you for considering my ideas and feature requests.

**Comment by gaveitatry** [comment]
3.) And here is one last request or suggestion.  It would be nice if we could add an automatic th, rd at the end of certain numbers.  And also consider having a capitalization option so it could be lower case 2nd and 3rd or upper case 2ND or 3RD.

**Comment by gaveitatry** [comment]
4.) Another idea that I just had.  When you do a onmouseover or mouse hover on the clock, it opens up a tooltip popup.  Instead of doing that, how about make it so that the clock text switches to alternative text in the same taskbar area?
So if the clock shows:
Saturday
4:54 AM
And you move the mouse over the time, it changes the text in the taskbar to something else like:
April 28
4:54 AM
or whatever you want it to say.

**Comment by White-Tiger** [comment]
well.. for most ideas, there's an issue for it.
Partial formatting: #141
Ordinal numbers: #80
Mouseover: actually my [README.md](../blob/master/README.md)

As for uppercasing some formats... not sure if I wanted that to be part of the format parser rewrite or if it's actually necessary to add because uppercase fonts could do the same. But that's for the future to decide.
Yet I imagined some function like format options which would allow that _(needed for ordinals)_

**Comment by gaveitatry** [comment]
Oh actually, I think that you misunderstood me about the mouseover idea that I had.

I don't mean tooltip popups.  I mean it would be cool to actually change the text on the taskbar itself, with no popups whatsoever.

So if if the taskbar says 8:29 AM, and you mouseover it, the 8:29 AM changes to something else like Saturday, April 28.  But in the taskbar, not in a popup.

**Comment by gaveitatry** [comment]
5.) Here is another idea that I had, but forgot to mention.  I started a stopwatch last night when I went to bed and left it running all night until I woke up.  It displayed how long I had been asleep.  So after I woke up, I wanted to start another stopwatch and leave it running in the background.  That way I would know how long I stayed awake.  Is it 12 hours?  Is it 18 hours?  How long do I usually stay up before I go to bed.  Well the thing is that the stopwatch won't run in the background.  There is no minimize button. I thought that I would be able to minimize it, and then later, right before going to bed, I could right click the time, go to the stopwatch menu, open up the window, and see how much time elapsed.  So this is a feature you don't have that I wish that you did.  And not only that, it would be pretty useless unless it remembered the time because what happens if you have to sign out or restart your computer?  I guess that I am asking too much.  On Windows 8.1, I used the default Alarms and it had a stopwatch that ran in background.  Even when the computer was restarted, it still remembered everything and kept on counting with no loss of information or time.  I am now on Windows 10, trying to get used to it, and that Windows 8.1 Alarm is no longer on my computer.  They have a new Windows 10 Alarms & Clock that is a little different.  It's okay, I guess, but I can't really get excited about it.  I didn't want to use these stupid apps.  I prefer using desktop programs instead of apps.  And since your app is so great and does a lot of what I want it to do, it would have been nice if it had this too.  I mean you have alarms, timers, and stopwatch.  I wish your stopwatch would run in the background, minimized and still resume counting time even after a system restart or signout.

**Comment by White-Tiger** [comment]
“mouseover customization, for example different time format, color, border or even current weather _tbd_”
