### ISSUE TITLE
Question about Mouseover Tooltip Text

### ISSUE THREAD

**Issue by gaveitatry** [White-Tiger/T-Clock#148]
For the mouseover feature, is there a way to add world clocks?  Like, if I am in UTC-6 and want it to display the time in UTC+2 in 12h format with AM/PM at the end, would that be possible?  Thanks in advance.

**Comment by White-Tiger** [comment]
nope... issues #32 and #73 handle this case.
the `w±` specifier only works for the hour part itself, but it doesn't affect other formats that follow it.

**Comment by gaveitatry** [comment]
Okay, thank you.
