### ISSUE TITLE
[FEA] Import default font settings

### ISSUE THREAD

**Issue by jerone** [White-Tiger/T-Clock#15]
It would be nice if T-Clock started with the exact same font, size, position, line height and style as used default by Windows.
Also a button to restore/revert any changed settings to the default would be nice.

**Comment by White-Tiger** [comment]
well.. I thought it's already using the same font..
What's wrong with T-Clock's look :P?

**Comment by jerone** [comment]
Here's a screenshot with above is T-Clock, below is normal Windows 7.
![tclock](https://cloud.githubusercontent.com/assets/55841/11447653/33517558-954a-11e5-946d-f8b3b2a71c5f.png)
Looking at the date, the font almost looks the same (default looks thicker). More different is the line-height & position.

**Comment by White-Tiger** [comment]
you mean **below** is T-Clock, right?

Well... my T-Clock uses some hacky drawing.. which tends to be a bit blurry *(though I have locally a dev version that supports different drawing methods and one being GDI+)*
T-Clock could in theory draw the very same text, but it would be forced to default color and font *(though background can change IIRC)*

And if you really want the "default" clock, you could also leave the custom format "empty"

P.S. how comes that you've got seconds?

**Comment by jerone** [comment]
> you mean below is T-Clock, right?

No the above one is T-Clock, the below one is Windows 7.

> P.S. how comes that you've got seconds?

That's an option from [7+ Taskbar Tweaker](http://rammichael.com/). If I enable or disable that feature nothing changes to style or position.

**Comment by White-Tiger** [comment]
if you're using the portable method, just re-execute the `.reset_portable.cmd`
Otherwise you'll have to delete the key from your Windows registry manually
`HKEY_CURRENT_USER\Software\Stoic Joker's\T-Clock 2010`

eg. through RegEdit or a .reg file
```ini
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\Stoic Joker's\T-Clock 2010]
[-HKEY_CURRENT_USER\Software\Wow6432Node\Stoic Joker's\T-Clock 2010]
```

*you'll loose all settings forever of course.. unless you create a backup*

**Comment by jerone** [comment]
Thanks!

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
