### ISSUE TITLE
[Feature Request] An option to control the size of line break gaps

### ISSUE THREAD

**Issue by scooterrodriguez** [White-Tiger/T-Clock#152]
My time is formatted like this: 
h : nn : ss \n\ndddd m/dd

It's cool and all, but for my tastes, there's too much empty space between the two separate lines. Yes, I know I'm using two line breaks in between the two separate lines. But if I remove one of the line breaks, I feel that then there's _not enough_ space between the two lines. Nit-picky, I know. It's a great program and I love it.

**Comment by White-Tiger** [comment]
well well, did you try `Clock Text -> Line spacing` :P?

**Comment by scooterrodriguez** [comment]
No, I did not. That's not mentioned (at least not explicitly) in the Help document, and reading the included instructions is about the extent of my abilities. 

Thank you anyway.
