### ISSUE TITLE
Week number incorrect

### ISSUE THREAD

**Issue by rwijtvliet** [White-Tiger/T-Clock#159]
Today, 2018-10-15, is the first day of week number 42 in Europe and according to ISO8601. My instance of t-clock, however, shows week number 41:

![grafik](https://user-images.githubusercontent.com/4106013/46931502-b144c980-d04b-11e8-96b0-68a5d5bda296.png)

My miscellaneous settings seem correct, too. 
![grafik](https://user-images.githubusercontent.com/4106013/46931513-bdc92200-d04b-11e8-8fb0-e40fcee03741.png)

From the help file:
Wi	= ISO 8601 numeric Week-of-Year. (Europe)

The pop-up calender _is_ correct:
![grafik](https://user-images.githubusercontent.com/4106013/46931587-1ac4d800-d04c-11e8-87e6-7842ef04fea2.png)

**Comment by White-Tiger** [comment]
which version are you using? Because it works on my end...

**Comment by rwijtvliet** [comment]
x64 2.4.2 build 459

**Comment by White-Tiger** [comment]
you should update to v2.4.4 then: https://github.com/White-Tiger/T-Clock/releases

**Comment by rwijtvliet** [comment]
That fixed it, thanks

**Comment by hoerbi1000** [comment]
im also having this issue with version 2.4.4

![image](https://user-images.githubusercontent.com/26603435/51457783-01ba7a00-1d53-11e9-89f0-10fc34df7e80.png)

![image](https://user-images.githubusercontent.com/26603435/51457789-07b05b00-1d53-11e9-8711-61c4f66e9247.png)

**Comment by White-Tiger** [comment]
what's the format you've been using?

**Comment by hoerbi1000** [comment]
I'm using an advancced clock format 

"KW"Ww - HH:nn:ss \n ddd, dd.mm.yy

**Comment by White-Tiger** [comment]
therein lies the problem.
`Ww` is the so called "Simple-Week-Number" format, it's not using the ISO standard you seem to want.
_(January 1st is always week one, 8th the second one)_
`Wi` would be the one to use.

**Comment by hoerbi1000** [comment]
thanks i will try
