### ISSUE TITLE
What is/are location/locations of config information for T-Clock?

### ISSUE THREAD

**Issue by stevebookman** [White-Tiger/T-Clock#16]
i.e. settings for different fonts, date format which user selects via mouse right click.  Windows 10.

**Comment by White-Tiger** [comment]
if you're using the portable method, it's `T-Clock.ini`
Otherwise it'll be in your Windows registry: `HKEY_CURRENT_USER\Software\Stoic Joker's\T-Clock 2010`

**Comment by jerone** [comment]
Might be good idea to put this information in the readme or wiki somewhere.

**Comment by White-Tiger** [comment]
to be honest.. I didn't even know that there is a wiki xD

But why do you need this kind of information?

**Comment by stevebookman** [comment]
Would be good to have a straightforward way (such as copy a single file) to other boxes to replicate a carefully tuned set of settings.

**Comment by White-Tiger** [comment]
That's what the portable mode is for...

Though import and export is also planned
