### ISSUE TITLE
[Feature request] 0-leading on "Wi" advanced clock format

### ISSUE THREAD

**Issue by 18steps** [White-Tiger/T-Clock#165]
I currently format like this:
```
yyyy mm dd\n"w"Wi "d"wi \nt HH.nn.ss
```
which gives (visually)
```
2019 01 08
  w2 d2
t 22.10.40
```
But for alphabetical reasons I like this:
```
2019 01 08
  w02 d2
t 22.10.40
```
which is **not currently possible**

### Current `Week of Year´ Date Options

> Wi	= ISO 8601 numeric Week-of-Year. (Europe)
> Wu	= U.S. like Week-of-Year – beginning on first day of the year, based on sunday
> Ws	= numeric Week-of-Year – beginning on first sunday.
> Wm	= numeric Week-of-Year – beginning on first monday.
> Ww	= SWN (Simple-Week-Number) numeric Week-of-Year. 

Note: Among all Date Options there is no use of single "W"

# Suggestion / Feature Request

> Add "W" in front of any "Week of Year" Date Option to *add a leading 0*

> // to week numbers `>= 0` `&&` `<= 9`.

### Introduce Additional `Week of Year´ Date Options
>WWi	= 0-leading ISO 8601 numeric Week-of-Year. (Europe)
WWu	= 0-leading U.S. like Week-of-Year – beginning on first day of the year, based on sunday
WWs	= 0-leading numeric Week-of-Year – beginning on first sunday.
WWm	= 0-leading numeric Week-of-Year – beginning on first monday.
WWw	= 0-leading SWN (Simple-Week-Number) numeric Week-of-Year. 

### Reason for `>= 0`

"-1" is equal in length to "00" and "01", "02", etc., while"-01" is 3 characters long.

Monospaced linebyline alphabetical sort aligns better with non-deviant length 2 than deviant 3.

#### Bad:
```
... Week 52 ... [aligned]
... Week -01 ... [misaligned]
... Week 00 ... [aligned]
... Week 01 ... [aligned]
```

#### Good:
```
... Week 52 ... [aligned]
... Week -1 ... [aligned]
... Week 00 ... [aligned]
... Week 01 ... [aligned]
```

### Precedence in leading 0 notation
From `T-Clock Help.rtf`:

>dd	= Numeric Day of Month (with leading 0) 
d	= Numeric Day of Month
...
mm	  = Numeric Month of Year (with leading 0) 
m	  = Numeric Month of Year

**Comment by White-Tiger** [comment]
You didn't try `WWi` yet, did you?

**Comment by 18steps** [comment]
😮😅 -- you're right.

Not sure if I should edit the original post, but I guess change the request to be to update docs with like a sentence.

**Comment by White-Tiger** [comment]
Well... I'd like to remove all "m / mm", "d / dd", "y / yy / yyyy" etc. entries because it's a simple syntax that everything should follow.. (well every format that displays numbers)
Yet, not everything supports white spacing with "_" as system uptime does.

**However, my currently unpublished documentation got this section:**
- **_**	 = Some formats support advanced padding.
	    Preceding these with underscores (_) will pad with up to X spaces.
	    Repeating the format specifier adds zero (0) padding to numbers with
	    less than X digits. (leading 0)
	    _eg._	___YY_ would result in "  03" if the year is "3"
		__YYY_ would result in " 003"
	    Currently supported by: **Y**, **S(d|a|h|n|s|T)**, **W(s|m|i)**
	    **Note: S** requires the padding after its initial **S** specifier, eg. _S_aa_
	    **Note: S** is the only one that supports spaced padding
