### ISSUE TITLE
"Update" icon is out from its button border

### ISSUE THREAD

**Issue by adem4ik** [White-Tiger/T-Clock#17]
Preconditions: Windows 7, Aero theme

1) Open "T-Clock properties"
2) Choose "About" tab
3) Press "Check for updates"

Result: "Update" icon is out from its button border
![image](https://cloud.githubusercontent.com/assets/4707112/11806262/e91fc8d6-a322-11e5-806e-b56b90fb3230.png)

**Comment by White-Tiger** [comment]
why should this be a bug?

**Comment by adem4ik** [comment]
feel free to close it if you don't feel so.

**Comment by White-Tiger** [comment]
sry I thought I've replied already...
From an aesthetic point of view *(which T-Clock isn't really anyway)*, do you dislike it and reported it as a bug for that reason?
Or do you know of any graphical or other issues it causes?

I would keep it this way unless there's a reason to change it... I actually though it'd be funny :P
*(though it was a coincidence and wasn't meant this way)*

Thanks for reporting and keep your eyes open ;)
