### ISSUE TITLE
Infinite loop at startup for HP 15 Laptop PC

### ISSUE THREAD

**Issue by aabatpurdue** [White-Tiger/T-Clock#174]
I have executed _tclock_ successfully on two (three?) other laptops running Windows 10 with no problems, one of which was an **HP Pavillion**.  However, on this **HP 15 Laptop PC** (as identified by _All Control Panel Items\Administrative Tools\System Information_), _tclock_ immediately goes into an infinite loop tying up one of 4 CPUs entirely.  Initially, _explorer.exe_ also ties up a CPU but quiets down after a bit.

Has anybody else seen this?

**Comment by White-Tiger** [comment]
I would guess you're using an old version... there used to be a bug like this.

**Comment by aabatpurdue** [comment]
I was attempting to use the  stable release.  Will try the  beta.

**Comment by aabatpurdue** [comment]
Yup, rc release candidate works.  Thanks.
