### ISSUE TITLE
Refreshing issues

### ISSUE THREAD

**Issue by juanmalunatic** [White-Tiger/T-Clock#176]
Hey folks, thanks for your time.

I'm running T-Clock Redux x64 2.1.0 build 57 on Windows 7. As great as the software is, sometimes the clock doesn't refresh for a long period (yesterday it was stuck for an hour).

Checking older issues I wonder if it's related to my custom time format (`hh:nn - ddd\n yyyy/mm/dd`). Could that be the problem? Are there guidelines for what works or doesn't?

**Comment by White-Tiger** [comment]
it should refresh once every minute (since you're not needing seconds), however, you're also using a very old version so the bug was hopefully fixed since then. I suggest that you update your version.

**Comment by juanmalunatic** [comment]
Upgraded to 2.4.4 build 492 and the issue seems to be gone, thanks!
