### ISSUE TITLE
我只是想简单诚恳的说声谢谢！！！！！！！

### ISSUE THREAD

**Issue by wywyne** [White-Tiger/T-Clock#187]
真的很棒，我找了好久具备这个功能的小插件，终于找到了，我就是想简单的表达下真心的感谢！太激动了！

**Comment by blackcrack** [comment]
很高兴您开心，但是
“问题描述”，因此“issue”仅将eigendlich用于问题，请关闭“Issue”
关闭并清理。
该按钮位于右下角的“评论/comment”旁边
和抢劫，关闭并评论

谢谢

其次，您在这里进行国际实习，
英语。

哦，您知道Reactos.org吗？
对于香港的学生来说是一件好事。
是一个WinNT
像微软一样
仅根据GPL许可，
所以是开放代码
任何人都可以加入

寻找它：
 www.reactos.org

**Comment by White-Tiger** [comment]
谢谢。 我很高兴它很有用。

Anyway, @blackcrack do you really have to advertise your stuff everywhere? Kinda looks shady to me this way.
btw, your translation had a spelling error...

**Comment by blackcrack** [comment]
Hi @White-Tiger ,
well i have use translate.google \*g* 
oder glaubst Du dass ich ein tausendsasser bin \*g*
if you found a error, can you fix it :)))) 

\*bow*
\*vbg*

And reactos can help peoples who fight for rights, if they are know, to be exist,
a advertising is more for commerciial  things, this is just a info..
More peoples have knowing about, more peoples can help, but is it concealed, it become forgotten..

best regards
Backy
