### ISSUE TITLE
Default Rightclick Option gets resetet

### ISSUE THREAD

**Issue by CloudeLecaw** [White-Tiger/T-Clock#192]
The default R-clickoption usually is to get the Kontextmenue where u cange change option.
i made a secound action for this (double click right) to get the menue and changed the default rightclick to the callendar feature.
The tool runs on startup. After a Windows restart the default action (the context menüe) for rightclicking is resetet in the options. all other settet interactions are saved correctly. just not this once.

So i assume this is a bug.

**Comment by White-Tiger** [comment]
nope... works for me :(
![image](https://user-images.githubusercontent.com/1467733/76346604-955b5b00-6305-11ea-9d74-4662e7a6e212.png)

btw, you can test this without restarting Windows by exiting T-Clock (through the menu) and then entering `shell:startup` as a file path into explorer and running the T-Clock there.
![image](https://user-images.githubusercontent.com/1467733/76346783-dbb0ba00-6305-11ea-8df0-88358fc15cf5.png)

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/76695175-64b85000-667c-11ea-8849-da5fcb0f018e.png)
Before restart
.
.
![image](https://user-images.githubusercontent.com/12080017/76695202-acd77280-667c-11ea-9608-8d9a153457f0.png)
After Restart

**Comment by White-Tiger** [comment]
you're right, it seems like my local version had already a fix for it...
currently context menu actions need to be on single click.

**Comment by CloudeLecaw** [comment]
is there a chance for releasing a nightly build or something like this which contains the fix allready? :-)

**Comment by White-Tiger** [comment]
I'll have to commit the changes first, but they were WiP so I would have to do some cleanup first... "nightly builds" would be automatic once I push the changes...

**Comment by CloudeLecaw** [comment]
Is it possible to release a new nightly version cotaining the fix? :)
