### ISSUE TITLE
Past month(s) option in Calendar settings works wrong

### ISSUE THREAD

**Issue by sfkulyk** [White-Tiger/T-Clock#2]
If I set to display 3 month and past month is 1, calendars opens with 3 month starting from current month, not past.

If I set past month to 2, calendars opens with 3 month starting from 2 month before current month.

Aim: I want to configure 3 month displays, with one before, one after and current month in the center.

**Comment by White-Tiger** [comment]
hmm... I'm only aware of the "new year" problem.. So what you described does indeed happen on January... though it works for every other month.
So.. the option to display one past month never works for you? What's your OS?

**Comment by White-Tiger** [comment]
Ok forget what I just said xD It's indeed a bug... It worked till the 29th of March ;) Because February doesn't have 29+ days... Looks like my little "hack" wasn't well thought-out

**Comment by sfkulyk** [comment]
I'm using windows 7 64bit.
today is 30 of march, and I see the same issue - 
"1 past month" - I see Mar, Apr, May
"2 past month" - I see Jan, Feb, Mar.
Will check in a few days, on April.

**Comment by White-Tiger** [comment]
solved in [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc)
