### ISSUE TITLE
I can't open T-Clock, although it is running (The clock is modified) after setting it up once.

### ISSUE THREAD

**Issue by LorenzHorvath** [White-Tiger/T-Clock#210]
Hey, I've just installed T-Clock yesterday, set things up the way I wanted them to be and so on, only to find out, that I can't open it again after the first time I launched it. Interestingly the clock still shows up on the taskbar. I run the latest version and have restarted the system (I set it up so it runs at startup), does anyone know how to fix this? Thanks in advance :)

**Comment by Umdog786** [comment]
I'm having this same issue. Just figured out that you simply need to right-click on the new date/time and you can access some quick settings. From there simply select "T-Clock Options" to get to the full options page.

**Comment by LorenzHorvath** [comment]
My savior! XD

**Comment by LynxusRen** [comment]
I just cant right click on the clock. It shows some obsolete time and IDK how to configure and all. Tclock was the best before this update. How can I accsess the older version ?
