### ISSUE TITLE
When using advanced time format the minutes is stuck on 07

### ISSUE THREAD

**Issue by 1333481** [White-Tiger/T-Clock#213]

**Comment by RahulMahesh62** [comment]
Hello, I too had the same issue. You can solve it by using n in the time format instead of m. n stands for the current  minute. 
You can try this: h:n:ss tt

**Comment by zemchuks** [comment]
works fine. thanks @RahulMahesh62

**Comment by ArthurWolfhound** [comment]
@1333481 - as an author of this issue - please **consider marking it as closed**, as the problem was at least partially resolved. If you'd like to report unintuitive or inconvenient UI please open new proper issue with correct request.

Kind regards, 
Friendly contributor to this issue madness

**Comment by 1333481** [comment]
@ArthurWolfhound thx for letting me know! thought I already did!
