### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by okuzster** [White-Tiger/T-Clock#219]
why is it using my cpu over 20% all the time?

**Comment by ArthurWolfhound** [comment]
Please do respect some basic logical guidelines about opening issues.
Do kindly provide, information about your PC/laptop such as processor, RAM, Graphics card (for systems which lack internal graphics or running G-SYNC or similar setups), provide information about your OS such as version, bit type (or use winver command in search, and then include screenshot), also do mind the fact that percentage for the usage in Task Manager is a relative unit of measurement and for low-performance systems it might be the case to report such amount of usage.

Please, **consider closing this issue** if you find provided information relevant, for the sake of sanity of the developer.

Do check actual usage via advanced tab. Including my own screenshots (i7-9750H, 32GB, RTX2060, Win10 Home 64bit)

![image](https://user-images.githubusercontent.com/16789106/89313238-eab35280-d680-11ea-9ddb-435892822185.png)
![image](https://user-images.githubusercontent.com/16789106/89313345-0b7ba800-d681-11ea-8227-971e175f94be.png)

Kind regards,
Friendly contributor to that issue madness

**Comment by okuzster** [comment]
sorry, my bad. pretty basic hardware, os here so i thought many should have same issue.

it is i5-9300H, 16GB ram, GTX1050, Win10 Pro N 64bit and a notebook

i did check from details tab also, and i removed t-clock since.

i re-activated t-clock now and cpu usage shows around 0%, i will post screen shots if i got the same issue.

i am leaving here open for now to see if it will happen again,

thanks for reply.

**Comment by suryapratap** [comment]
I keep getting constant CPU usage at 6% on win 10 , I have an i9 processor, the clock display does not show up and explorer restarts atleast once after  starting the application

![image](https://user-images.githubusercontent.com/956538/117439610-ad059200-af50-11eb-9d71-30cf4df291fe.png)
