### ISSUE TITLE
Advanced clock format string looks squished

### ISSUE THREAD

**Issue by WonderRat** [White-Tiger/T-Clock#22]
T-Clock Redux v2.4.0 (beta 3, build 384)
XP SP3 (Russian)
![20160214002](https://cloud.githubusercontent.com/assets/17234818/13034415/bd6b96d4-d356-11e5-874c-ed9badeda5d8.png)

**Comment by White-Tiger** [comment]
my current local build got converted to Unicode, which includes a change to the font used for the advanced format box.
So your issue is likely "resolved" there.

**Comment by White-Tiger** [comment]
v2.4.1 likely fixes this issue
https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.1%23414-beta
