### ISSUE TITLE
Explorer keeps crashing

### ISSUE THREAD

**Issue by rarespizaa** [White-Tiger/T-Clock#245]
When I start clock.exe, my fans go loud and my taskbar freezes. I can **Ctrl+Shift+Esc and kill Explorer and T-Clock**, but when I open clock.exe again, the same thing happens *again and again...* 

**Please note that I am not using _TaskbarX_ or other taskbar tools.**
Using Windows 10 Pro 20H2 (build 19042.804)

**Comment by jiping-s** [comment]
Same here. Taskbar freeze, clock running at 100% CPU. Windows Server 2019 (1809).

**Comment by ghost** [comment]
Same here. Any fixes?

**Comment by rarespizaa** [comment]
Has anybody found a fix for this? I used to love this tool, but I can't use it. On my Windows 7 Ultimate laptop it works just fine.

**Comment by rahmanrafi** [comment]
I was having the same problem with 2.1, but if you use the latest pre-release version, it works fine on 20H2.

**Comment by Chaussettes99** [comment]
Am having the issue as well. Anytime I try to run Clock.exe, explorer shoots up to 50% CPU and stops responding without T-Clock working. On windows build 20H2.

**Comment by etherxrs** [comment]
using the pre-release (v2.4.4) could help, if anyone else still has problems

**Comment by rarespizaa** [comment]
Thank you! 2.4.4 works just fine. I'll close it so others can observe the solution too!
