### ISSUE TITLE
T-clock not showing week number even after checking the "Show week numbers" box

### ISSUE THREAD

**Issue by kiran-sorama** [White-Tiger/T-Clock#259]
![image](https://user-images.githubusercontent.com/87006093/124565077-f46da900-de41-11eb-9bdc-0530870ec422.png)

**Comment by blackcrack** [comment]
https://github.com/White-Tiger/T-Clock/issues/256#issuecomment-871301734

**Comment by mbaas2** [comment]
I guess you meant "not"?

This is not a bug, but a misunderstanding: this checkbox shows the weeknumber in T-Clock's **calendar** (as the caption suggests). 
If you want to permanently see the weeknumber of the current day, customize the "Time format" -> "Advanced clock format". (Use the link there to see available formats)

**Comment by mbaas2** [comment]
> [#256 (comment)](https://github.com/White-Tiger/T-Clock/issues/256#issuecomment-871301734)

@blackcrack I appreciate that you seek attention for your issue, but spamming every other discussion with that link will probably not help a lot...

**Comment by kiran-sorama** [comment]
Thanks a lot @mbaas2 ! Sorry for the typo in the question. Your solution worked! 
I used `hh:nn:ss tt\n "Week" Wi ";" dd/mm/yy`

**Comment by blackcrack** [comment]
@mbaas2  Hi Micha, nö, so wie ich mitbekommen hab, wird T-Clock nicht mehr weiterentwickelt von @White-Tiger  und nicht mehr gesupported vom René .. hab seit längerer Zeit irgend wann sogar auch ne Mail bekommen...  Hättest Du nich lust ?
Man sollte normalerweise in der Readme.MD auch noch rein tippern, daß T-Clock nicht mehr gesupported und weiterentwickelt wird

**Comment by mbaas2** [comment]
@blackcrack Sorry, ich da kann da entwicklungsmäßig nix machen. Außer vlt. mal mit Hinweisen bei Themen wie diesem helfen.
Bin ansonsten auch "nur" ein "happy user" (W10, bei mir funzt alles 😉)

**Comment by blackcrack** [comment]
> 
> 
> (W10, bei mir funzt alles wink)  
\*lol* :+1:  unten im keller Fedora, Workstation Win7  mit aktuelle patches.. die ich dann noch extra downloade.. mit vbox mit allem und nem 43"LG UHD, gegenüber Schiebefestplatten Kiste mit zwei Monitore
wenn de n bisschen schmökern willst : [blackysgate.de/files](http://blackysgate.de/files) :wink: 
Das heist "Extended User", die happys sind luschen, die Lassen Ihr win wie es iss, guggst Du in Deskmodder.de Block, da hat letztens einer gegen Modder geschossen und wurde alles gelöscht \ Die extended treiben sich hier rum und veruchen vieles weiter zu bringen und passen Ihr win an wie es Ihnen gefällt.. \*kicher* nuja, bin seit den BBS'es über Modem&Term nu dabei, iss nu auch schon mehr als 20 Jahre her das man unser HL ein bisschen gepuscht hat n sinne von Soft.. aber bin immer noch Anwender geblieben, weil sich's noch nie ergeben hat, aber mach jetzt nen IT-System Elektroniker, da kommt dann das programmierer frei Haus.. \*g* mal schauen.. Phython auf jedenfall und mal sehen wie's mit c und c++ iss.. also viel spaß mit rumbuddeln hier in Github.. und lass Gitlab nich aus.. auch wichtig.. gehört ned MS... \*winke*
