### ISSUE TITLE
How to quit T-Clock properly

### ISSUE THREAD

**Issue by dg9ngf** [White-Tiger/T-Clock#27]
How can I quit the Clock application properly in code? Killing the clock.exe process doesn't work. The process will be gone but the running clock will remain in place, out of control. An Explorer restart is nesessary to recover from this. In the code, the IDM_EXIT command is handled, but I'm not sure for which window, and how to easily find that. Is there some clock.exe command line parameter to quit things properly? clock /? doesn't do anything and there's no documentation about it.

**Comment by White-Tiger** [comment]
no documentation about it :P?
https://github.com/White-Tiger/T-Clock/blob/master/Release/T-Clock%20Help.rtf
/exit should work ;)

**Comment by dg9ngf** [comment]
Oops, didn't see that at the end. I only noticed the other pages before that. Thanks, that helps.
