### ISSUE TITLE
Alarm between midnight and 1am doesn't work

### ISSUE THREAD

**Issue by njwgh** [White-Tiger/T-Clock#3]
I am using 64-bit 2.3.2 build 151.
OS Windows 7 64 bit
If I set an alarm to go off between midnight and 1am then it actually goes off between noon and 1pm
I am using a 12 hour clock
So what is happening is that alarms set for 12:30am and 12:30pm are both going off at 12:30pm
I haven't tried with a 24 hour clock
Thanks

**Comment by White-Tiger** [comment]
bug confirmed, will fix that with the next release

**Comment by njwgh** [comment]
Thanks! :-)

**Comment by White-Tiger** [comment]
solved in [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc)
