### ISSUE TITLE
UpdT dword registry value is 8 bytes long (Win7/64)

### ISSUE THREAD

**Issue by B00ze64** [White-Tiger/T-Clock#30]
Title says it all :-)
The DWORD value UpdT is in fact 8 bytes long under Win7/64.
T-Clock Redux v2.4.0ß.
Regards,

**Comment by White-Tiger** [comment]
it's a QWORD, what did you try to say?

**Comment by B00ze64** [comment]
It's typed as a DWORD. Either you are pushing 4 extra bytes into it, or you wrongly specify the value as a DWORD when you create it. Look at it with regedit, you'll see it complains about it...

**Comment by White-Tiger** [comment]
hmm... now I see what you mean... Just what the hell Microsoft...
I've tested all those functions, and they did what I wanted them to *(even though the writing code was wrong, yet the reading one is correct.. but still seemed to work even though it actually checks for QWORD)*

I didn't know Windows would simply store anything you're passing...

Anyway.. will be fixed when I've got time to continue working on T-Clock *(there are a lot local changes already)*

**Comment by B00ze64** [comment]
Lol, amazing isn't it, we tell it to please create a 4 byte value, then give it 8 bytes and it doesn't say a word, stores all 8 bytes in the database ;-) No rush on fixing, it works regardless. In the meantime, I discovered we can create a INI file and share settings between accounts, because you included a BAT that creates an empty INI file hehe, so that's what I use now - this way Administrator and my normal user account both share the settings without me having to export the registry between users :-) Thanks!

**Comment by White-Tiger** [comment]
for the sake of completeness.. this issue was originally reported here: http://donationcoder.com/forum/index.php?topic=21944.msg396909#msg396909
