### ISSUE TITLE
Option to disable automatic update check

### ISSUE THREAD

**Issue by ganego** [White-Tiger/T-Clock#31]
Please add an option to disable automatic update check.

**Comment by White-Tiger** [comment]
you can already do so when an update was found.. or simply create the setting manually as described in other issues.
Also, it's directly build into the about UI in my local developer build (not release yet)

**Comment by White-Tiger** [comment]
thought I had another issue about it.. well anyway, here's a forum post for a workaround if update checking isn't possible for some weird reason:
http://www.donationcoder.com/forum/index.php?topic=21944.msg391378#msg391378
