### ISSUE TITLE
Starting the prog

### ISSUE THREAD

**Issue by frewys** [White-Tiger/T-Clock#33]
I have used the original one and the modified ones
Happy I found the updated version. Thanks.

My issue is it won't start at all.
After I put the required DLL file in there I can start the prog. But it won't take over the task clock.

I am on win10x64

Thanks

**Comment by White-Tiger** [comment]
what required DLLs?

**Comment by frewys** [comment]
It asked me for msvcr100.DLL for both this and tclock 2010. It worked on it but I could never get it to show up on your build

**Comment by White-Tiger** [comment]
well.. if you really want to copy the dependencies manually, you should have to also add them to the misc/ folder..
Though it is recommended to install the proper dependency as stated on the main page:
https://microsoft.com/en-us/download/details.aspx?id=26999

**Comment by frewys** [comment]
Thank you for your quick responses

That did it for me. Also placing the DLL in misc worked like a charm. Now T-clock shows up in my tray like it should.

Looking forward to using the app beyond 2016 :+1:

**Comment by White-Tiger** [comment]
if you really don't want to install the redistributable.. Why not simply use the static builds which don't have this dependency?

**Comment by frewys** [comment]
Is there a link?
I have only seen this:
https://github.com/White-Tiger/T-Clock/releases
