### ISSUE TITLE
Days left

### ISSUE THREAD

**Issue by okmoon** [White-Tiger/T-Clock#34]
ex) \n D-29 "10th Wedding Anniversary" \n D-50 "Daughter Birthday"
I used text formats  for the schedule reminder
But have to change text of days(D-XX) day after day
how can i show days left on taskbar automatically?

**Comment by White-Tiger** [comment]
this is currently not possible with T-Clock

**Comment by okmoon** [comment]
Thank you for your answering me
It's so useful program to me
I really appreciate what you made :)
