### ISSUE TITLE
Calling Win10 Calendar by multiple clicking produce delay

### ISSUE THREAD

**Issue by adem4ik** [White-Tiger/T-Clock#35]
Version: v2.4.0 (beta 3, build 384)
OS: Windows 10 x64 version 1511 build 10586.318
Locale: Russian

1) Make a double-click by left mouse button on clock (so calendar won't appear)
2) Make a single left mouse click on clock

Result: calendar appears in 5-10 seconds after the last click
Expected result: calendar appears shortly after the last click

**Comment by White-Tiger** [comment]
non-English Windows?

**Comment by adem4ik** [comment]
`non-English Windows?`
right, I'm using Russian locale

**Comment by White-Tiger** [comment]
that might be the cause^^ there's currently nothing I can do about that (it still is WIP)
it's actually uncertain if this will / can ever change without hooking deeply into Windows (which I wouldn't do just for that)

**Comment by White-Tiger** [comment]
well.. it's not really fixed for the real Win10 release, but the 1st Anniversary update luckily made any adjustments "unnecessary" since Win10 is forcing updates anyway...
So v2.4.1 should fix this ;)
https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.1%23414-beta
