### ISSUE TITLE
Windows 10 Anniversary Update Issue

### ISSUE THREAD

**Issue by blueWeber** [White-Tiger/T-Clock#41]
issue #1: show below image
http://blueweber.cafe24.com/temp/tcbug.jpg

issue #2: when mouse left click, don't appear windows calendar

**Comment by acethical** [comment]
Same.
Insider, release preview channel, updated from 10586 to 14393.5.

**Comment by White-Tiger** [comment]
duplicate of #39

**Comment by White-Tiger** [comment]
Alpha/Beta *(something probably unstable)* release here: https://github.com/White-Tiger/T-Clock/releases
