### ISSUE TITLE
Beta loses text color when T-Clock Hovered

### ISSUE THREAD

**Issue by rebop** [White-Tiger/T-Clock#43]
Just installed and thanks for updating this! I have time color set to red. As soon as I hover that area of the tray, it turns white. Can repeat multiple times.

Can this be fixed? Not the end of the world, but nice to have.

~Bob

**Comment by White-Tiger** [comment]
whoops... that's actually something I didn't test xD should have known better... :(

**Comment by rebop** [comment]
Hi Rene,
 
I have build 414 and not fixed. Is it another build that incorporates this
fix I can try?
 
Thanks.
 
~Bob

  _____

**Comment by White-Tiger** [comment]
it simply wasn't released yet^^ And Github keeps closing issues when I write "fixes #xx" in my commits.. I usually try to keep them open until it's build and fully released _(so they'll get a notification)_
Don't blame me :P 

Anyway, get it here: https://github.com/White-Tiger/T-Clock/releases _(the MSVC build is currently buggy.. but using the static one should be fine as well)_

**Comment by rebop** [comment]
Thanks :)

  _____
