### ISSUE TITLE
One or two-digit week numbering

### ISSUE THREAD

**Issue by subtrEM** [White-Tiger/T-Clock#44]
A request to improve week numbers (in ISO format): in industry and production environments, dates are frequently abbreviated to (2-digit) year + (2-digit) week number. So e.g. Thu 4 Aug 2016 would be shown as **1631**.4 (year 2016, week 31, day of week 4). T-Clock approximates this using the clock format "yyWi.ddd", except for one-digit week numbers. So the request: can (ISO) week numbers be shown 2 characters wide, with leading 0 added for weeks 1-9?

Looking into the sources in T-Clock/src/DLL/format.c (version 3 Aug 2016), a quick and dirty change could be in line 378:
`out += wsprintf(out,"%02d",week);       // format "%d" to "%02d"`
A more elaborate change could be to support a format like Wi or WWi to signal one or two-digit week numbering.

**Comment by White-Tiger** [comment]
btw, don't think I've ignored your first post here: http://www.donationcoder.com/forum/index.php?topic=21944.msg398901#msg398901
It's just that Github is easier to keep track xD

The bug fix release includes your request now.
https://github.com/White-Tiger/T-Clock/releases

**Comment by subtrEM** [comment]
Thanks for the quick reaction. Glad this project is still quite alive.
-Eric
