### ISSUE TITLE
Update checker needs to respect proxy settings

### ISSUE THREAD

**Issue by zommuter** [White-Tiger/T-Clock#48]

**Comment by White-Tiger** [comment]
it already respects system wide proxy settings.

**Comment by zommuter** [comment]
Strange then: 

![t-clock no update](https://cloud.githubusercontent.com/assets/3686260/17554330/a97bf35e-5f0a-11e6-9ced-d82a55313502.png)

The error message should be more specific than `<ERROR> connection issues`, I merely guessed it's the proxy setting because that is usually the culprit...

**Comment by White-Tiger** [comment]
well... T-Clock doesn't use IE's proxy settings, so if you've configured those, but not those of your system, it won't use any proxy.

**Comment by zommuter** [comment]
Hm, I configured all proxy settings I can think of, including e.g. the environment variable `HTTP_PROXY` for git. However, the corporate firewall used [WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Autodiscovery_Protocol), maybe that negatively interferes?

**Comment by zommuter** [comment]
The error is produced in [update.c, line 393](https://github.com/White-Tiger/T-Clock/blob/2be1843fa1e285b4d1f73976e21eff812f1f2e7e/src/options/update.c#L392-L394), and `WINHTTP_CALLBACK_STATUS_REQUEST_ERROR` is [documented](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383917(v=vs.85).aspx) as

> An error occurred while sending an HTTP request. The _lpvStatusInformation_ parameter contains a pointer to a [WINHTTP_ASYNC_RESULT](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384121(v=vs.85).aspx) structure. Its **dwResult** member indicates the ID of the called function and **dwError** indicates the return value.

Unfortunately I don't have a suitable compiler or too much time to check _lpvStatusInformation_ but I guess that's the info I'd need to see why my system doesn't update.

Obviously this is a very low-priority problem though, aside from that T-Clock is plain awesome!

**Comment by White-Tiger** [comment]
Well.. does `netsh winhttp show proxy` claim that you've got a proxy set?
See this for how to configure a system wide proxy: http://superuser.com/a/649158

**Comment by zommuter** [comment]
Yet _another_ proxy setting? Sigh... Thanks, yes with that setting it works then.
