### ISSUE TITLE
T-Clock strange behavior

### ISSUE THREAD

**Issue by JLOBoyle** [White-Tiger/T-Clock#49]
After having installed the Windows 10 Anniversary update, my version of T-Clock no longer worked.  I found yours yesterday, and installed it on for systems.  Today TWO of the systems exhibit a strange anomaly.  The “minutes” digits don’t increment beyond “8”.  The seconds rollover at “60”, and apparently the hours roll over at the appropriate time, but the digits are stuck on”08”.

If I exit T-clock, the regular clock shows the correct time.  If I restart T-Clock, the “08” returns.

Anyone have any thoughts as to what I might be doing incorrectly?

Thanks.
JLOB

**Comment by White-Tiger** [comment]
what's the format string you're using?

**Comment by JLOBoyle** [comment]
Thanks for the clue!  I really appreciate it.  I was TRYING to use "ddd. 
d mmm yyyy h:nn:ss tt".  I keyed "ddd. d mmm yyyy h:mm:ss tt"!!  I might 
have noticed it when we got to September, but doubtful.


Thank you.

JLOB

**Comment by White-Tiger** [comment]
seems to be "fixed" then ;)

**Comment by JLOBoyle** [comment]
'Tis.  Gracias.
