### ISSUE TITLE
Trying to view TClock calendar yields: MSVCR100.dll missing (that is not missing)

### ISSUE THREAD

**Issue by verbatim** [White-Tiger/T-Clock#5]
![msvcr100](https://cloud.githubusercontent.com/assets/314200/8321754/d8fa84f4-19f8-11e5-924e-ea522ce84bd2.jpg)

"The program can't start because MSVCR100.dll is missing from your computer. Try reinstalling the program to fix this problem.

I do have it installed. See grab.

Any help is much appreciated.

**Comment by hspindel** [comment]
Try right-clicking MSVCR100.dll and select Register DLL.

At 07:39 PM 6/23/2015, verbatim wrote:

**Comment by verbatim** [comment]
![msvcr100_no_register_option](https://cloud.githubusercontent.com/assets/314200/8331541/f557e6ec-1a56-11e5-9682-4be73cc0ca18.png)

Thanks for getting back so quickly. I don't see "Register DLL" in the right click.

**Comment by White-Tiger** [comment]
actually, this is because you've only installed the 64bit version of the VC++ runtime.
Please also install the 32bit runtime: http://microsoft.com/en-us/download/details.aspx?id=26999 (vcredist_x86)

**Comment by verbatim** [comment]
Thank you so much. That did solve the problem.

I figured I only needed to install the 64 as I am on a 64 computer.

**Comment by hspindel** [comment]
Then Google for how to register DLLs manually:

http://ss64.com/nt/regsvr32.html

http://stackoverflow.com/questions/4897685/how-do-i-register-a-dll-file-on-windows-7-64-bit

At 06:54 AM 6/24/2015, verbatim wrote:
