### ISSUE TITLE
Win 10 Default Calendar support is broken again

### ISSUE THREAD

**Issue by bilago** [White-Tiger/T-Clock#50]
I worked with you in Sept of last year to get the default Windows 10 calendar working. Well I decided to update to your latest version today and now the calendar no longer works. When I click on the clock I do see explorer.exe increasing in memory size consistently without ever going back down so there is a memory leak in regards to this as well.

Pressing the clock creates a rundll32 process as well.

**Comment by White-Tiger** [comment]
seems like your Windows is damaged... AFAIK rundll32 is used by the explorer to launch the calendar... so T-Clock seems to do everything right _(besides the latest version only "emulates" a mouse clock on the original clock, so there isn't anything else it does)_

Can you verify that even the Windows' own clock shows this bug?

**Comment by tester2011** [comment]
I have the same issue - clicking on the clock no longer shows the calendar. Mine is a fresh install of Win 10 Pro 64-bit 1607.

Cheers,

Mike.

**Comment by mikolajek** [comment]
I believe **it's random** - I have three laptops with Anniversary Update and on two I can bring up calendar with no problem while on third nothing happens when I click T-Clock face. All three machines run almost identical software configurations due to the way I use them.

**Comment by White-Tiger** [comment]
@mikolajek does your 3rd PC always exhibit this behavior?

Also, are we talking about Win10 or Anniversary update?
Does anyone of you use some untypical setup? Eg. touchscreen instead of mouse, Right mouse button acts as the left button or something?

**Comment by mikolajek** [comment]
Yes, my 3rd PC suffers from calendar not being brought up when T-Clock is fixed. All my machines have been updated to the Anniversary Update.

I cannot really tell the possible reason, as - quoting my above post - the configuration of all three machines is almost identical. I'm saying almost as I try to keep it similar, but in certain cases I may install some extra software on the particular machine. And the one that suffers from this issue is actually the one I treat as "trashy" PC - this is the one for private use (others are for business). So it may mean that some piece of software actually interferes with T-Clock.

**Comment by White-Tiger** [comment]
though, did you verify that the calendar works when T-Clock isn't running? That is, the calendar usually works with the default clock?

**Comment by mikolajek** [comment]
Yes, with no T-Clock running, the calendar appears with no issues.

**Comment by White-Tiger** [comment]
Did this release change anything?
https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23445-beta

**Comment by tester2011** [comment]
Didn't work for me - T-Clock won't even start. Gives a DLL error (MSVCR100.dll is missing).

Previous stable release 2.4.1. build 419 doesn't give this error.

Cheers,

Mike.

**Comment by White-Tiger** [comment]
use the static build :P

**Comment by tester2011** [comment]
Opps! Okay, this seems to work fine on my system (Win 010 Pro 64-bit 1607)

Cheers!

Mike.

**Comment by White-Tiger** [comment]
I'm closing this as I believe the issue is fixed... the [new version ](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23459-beta) includes a slightly modified version of 95446ff
