### ISSUE TITLE
Autostart Not Working: Windows 10 x64

### ISSUE THREAD

**Issue by Bowch** [White-Tiger/T-Clock#52]
Hi

I've been using T-Clock for a while now and love it.  I just have 1 bugbear, and it's not a huge one anyway!  It doesn't seem to want to autostart on my system; I can go and manually run it fine.  Although, I have noticed that after going back to my PC hours later that it's no longer running and I just have to start it again.  I have a feeling that it may be after my monitor goes to sleep (which is set for 5 hours), but I am not 100% certain on that.

Mini-Specs:  AMD Phenom II X4 955BE, 8GB RAM, 4GB ASUS R9 380x, 120GB SSD and Windows 10 x64 v1607 Build 14393.51 with other drives and network mappings.

[msinfo32.txt](https://github.com/White-Tiger/T-Clock/files/412897/msinfo32.txt)

It start up fine on my Win 7 x64 work machine.

**Comment by Bowch** [comment]
Meant to add that it's been doing this for months on prior Windows 10 builds.

**Comment by White-Tiger** [comment]
could you try to uncheck the startup option, apply changes and then check it again?
Also, from your report file, it seems like your T-Clock runs elevated? did you apply any kind of compatibility mode like XP or run-as admin or something?

**Comment by Bowch** [comment]
I tried running it as admin to see if it'd run on startup.

I've also tried unchecking the startup option, applying changes and trying again without success.

**Comment by Bowch** [comment]
Holy crap...

Just tried again:  I disabled the run as admin option; disabled and re-enabled the autostart, rebooted, and it autostarted...

I work in IT and swear that I did that a number of times previously; I know how many times users lie about doing things as instructed!

Anyway, not an issue any more!
