### ISSUE TITLE
Numeric day of the week

### ISSUE THREAD

**Issue by cagdasatici** [White-Tiger/T-Clock#53]
Hello White Tiger,

It would be very beneficial to have a functionality to display the numeric day of the week. Especially for people using the weeks and days in the format as wk32.4 to denote the Thursday of week 32 (today). I have stumbled upon this request: https://www.donationcoder.com/forum/index.php?topic=21944.msg398901#msg398901
However, using "yyWi.ddd" displays "wk32.Thu" not "wk32.4". I am using the v2.4.1 - the latest as of today.

Thanks,

-Cagdas.

**Comment by White-Tiger** [comment]
Added in https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23459-beta

**Comment by cagdasatici** [comment]
Thanks a lot!!! I appreciate your quick response.
