### ISSUE TITLE
T-Clock bottom right got cut off

### ISSUE THREAD

**Issue by shawnboy99** [White-Tiger/T-Clock#54]
Running T-Clock Redux x64 2.4.1 build 419 on Windows 8.1 with Classic Start Menu 4.3.0 (current version).

When first starting T-Clock after logon, the display looks like this:
![image](https://cloud.githubusercontent.com/assets/20984221/17614107/61baf358-6018-11e6-9967-6dc3cb3896cf.png)

It stays like that until a "Refresh T-Clock", then it looks OK like this:
![image](https://cloud.githubusercontent.com/assets/20984221/17614137/95155450-6018-11e6-94de-db377bfb2f72.png)

Any help toward fixing this is appreciated!

**Comment by White-Tiger** [comment]
if you adjust the clocks size by ±1, does it still occur?

**Comment by THEtomaso** [comment]
It seems that T-Clock doesn't refresh itself properly when the taskbar is hidden.

**Comment by White-Tiger** [comment]
@shawnboy99 can you confirm that your taskbar is also set to auto-hide ?

**Comment by White-Tiger** [comment]
Issue should be fixed here: https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23445-beta
Report back if there are any problems
