### ISSUE TITLE
Timer watch

### ISSUE THREAD

**Issue by nickodemos** [White-Tiger/T-Clock#55]
Searched long and hard to find something I could use till I found T-Clock, so for this I say thank you. 

Issue I have is that it would be nice to be able to reset an alarm in the timer watch window. I play games and after completing something I have a set amount of time to wait till I can do it again. So it would be nice to have the timer watch window pop up with all listed alarms to see what needs done and also be able to reset it from the timer watch window. As it is there are multiple steps involved to do a reset and this can be a bit of a hassle doing it 10+ times a day.

Either way I plan on using this for the foreseeable future.

-edit
Also noticed just now that I can't resize the timer box for more timers, IE I have slider bars now to look for said timers, and was wonder about being able to resize this.

Possible to also get it so that timers can be sorted either by name or time left till next goes off?

**Comment by White-Tiger** [comment]
so in regards to the "restart timer" feature, you're expecting a context menu for the watch list, right?

**Comment by nickodemos** [comment]
Would it be possible add a connection to your T-Clock Timers context menu and add it to the entire screen of the Timer Watch box so that right clicking anywhere would just link it to that context menu. Would have the extra benefit in seeing which timer stopped that way unless we had an option of leaving all timers in the watch box even at 0.

That might be easier than what I was thinking and make each timer a button to reset.

**Comment by White-Tiger** [comment]
do you think you'll be missing anything?
![](http://i.imgur.com/TomrX9r.png)

**Comment by White-Tiger** [comment]
does this work for you?
https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23445-beta

**Comment by nickodemos** [comment]
Love it. Works well
