### ISSUE TITLE
T-Clock x64 creates autostart shortcut to incorrect (x86) programs directory

### ISSUE THREAD

**Issue by zieren** [White-Tiger/T-Clock#59]
On a German Windows 7, when I check "Start T-Clock Redux when Windows starts" it creates a shortcut to:

"C:\Program Files (x86)\T-Clock\Clock64.exe"

However, the correct path is:

"C:\Program Files\T-Clock\Clock64.exe"

This is where 64bit files are installed, hence I manually installed the program there. Maybe just check the filename of the running binary?

**Comment by White-Tiger** [comment]
T-Clock is already using the path of the currently running executable...

**Comment by zieren** [comment]
I have no binary installed in this path ("... (x86)..."), and Process Explorer shows the current executable's path as "C:\Program Files\T-Clock\Clock64.exe".

**Comment by White-Tiger** [comment]
Can you confirm that this always happens when you remove the autostart and then add it again?
I can't currently reproduce the issue

**Comment by zieren** [comment]
Yes, I retried twice. After removing the incorrect .lnk the checkbox is unchecked; when I check it again the incorrect .lnk is created. Fixing the .lnk has no effect in the UI. There is also no other *clock*.lnk file on the c: drive.

What version of Windows are you using? I'm using Win7 Professional in German.

**Comment by White-Tiger** [comment]
I've tested it under Win7, Win10, Win10 Anniversary and all show the expected behavior _(though, only Win7 and Win10 Anniversary were tested with and without UAC)_

**Comment by White-Tiger** [comment]
The latest version: https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23459-beta
shouldn't change anything, though you might try it nonetheless..

**Comment by zieren** [comment]
Sorry, same thing.

**Comment by White-Tiger** [comment]
hmm... I'm out of clues actually.. I don't see what might possibly break it.
If you're interested in having it fixed, and you're not finding ways to reproduce it eg. inside a virtual machine or 2nd PC, I could only offer a TeamViewer session to take a look at it myself... _(for that, contact me by email or PM me on DonationCoder forums)_

**Comment by zieren** [comment]
Never mind, it's not a high priority. Thanks for the offer and the quick response!

**Comment by White-Tiger** [comment]
if still possible, could you try the new release: https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc
and see if that fixed it?

**Comment by zieren** [comment]
Yes, it's fixed now. Thanks!
