### ISSUE TITLE
Calendar doesn't seem to work on Win10

### ISSUE THREAD

**Issue by Baegus** [White-Tiger/T-Clock#6]
Clicking the clock doesn't do anything on Windows 10.

**Comment by White-Tiger** [comment]
I didn't fully check Win10 yet, but thanks for your support so far ;)
Will to a full check (and fixed when possible) shortly before next release.. (which to be honest, is due by 2-3 months already :/ And will take at least 2-4 days if I fully work on it)

**Comment by qwerty12** [comment]
It works if you call PostMessage to bring up the calendar instead of SendMessage but I don't know if doing so breaks anything for past Windows versions and I just applied the Registry tweak to bring back the old, non-XAML based clock anyway...

**Comment by White-Tiger** [comment]
the reason why I've been using SendMessage is simply that I want to wait for the message to be received. Not sure if it's really needed, but it should be better. Not sure why PostMessage could make a difference here.

But what XAML based clock?

**Comment by qwerty12** [comment]
Honestly, I am not sure as to why it works, but I can confirm that it works for me in both a VMware install of 10 and my actual install. I guess someone who has a copy of Visual Studio handy and can literally replace `SendMessage` with `PostMessage` can verify this.

> But what XAML based clock?

In Windows 10, the Windows 7/8 clock and calendar applet has been replaced with a new [one](http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2015/07/Enable-Windows-7-Like-Clock-Calendar-in-Windows-10-Taskbar.jpg) (in case of hotlink protection: [here](http://www.thewindowsclub.com/enable-old-windows-clock-calendar-windows-10)) and for this clock, T-Clock calling SendMessage would not display it at all. I used the Registry tweak on that page to bring back the old clock, and I'm presuming SendMessage does start working once again - I know that my build that still calls PostMessage has no problems showing the old clock.

**Comment by White-Tiger** [comment]
Good to know about that... I knew about that new calendar, but didn't knew that it can be changed.
So I'll add not only a way to open the new calendar, but also an option to re-enable the old one.

**Comment by verbatim** [comment]
White-Tiger - Thanks for the update. I also get the same error that the calendar cannot run

![screen_cap_win10](https://cloud.githubusercontent.com/assets/314200/9065445/82d475ea-3a9f-11e5-9633-7d95d077c194.jpg)

XPCalendar.exe - Application Error
The application was unable to start corectly (0xc000007b). Click OK to close the application.

**Comment by bilago** [comment]
Any update on this? Calendar still not working on Win10

**Comment by White-Tiger** [comment]
so... you can compile yourself?
I have a fix for it locally, not yet pushed to github, but could do so if you need it.
It currently only supports English versions of Windows though (the multi-monitor support)

PostMessage() should have worked.. but I'm using SendMessageCallback()

**Comment by bilago** [comment]
Yes, I compiled it using Visual Studio 2013, clicking the calendar did not work with the change I mentioned above.

**Comment by White-Tiger** [comment]
I actually didn't want to close this (and other issues) until the final version is out.. but what ever xD
Anyway, can you try it bilago and report back?

The version should be already more stable than my previous ones.. though it's not finalized and thus the settings converter runs at every start^^ (though, shouldn't be a problem unless you try to use the 12h and 24h format together..)

That much said, I try to publish a pre-release this weekend if I'm still not ready for the release (but it should be close)

**Comment by bilago** [comment]
I'm not seeing a CI build available for download on https://travis-ci.org/White-Tiger/T-Clock or AppVeyor, should I just download your repo again and build myself?

**Comment by bilago** [comment]
Unfortunately this latest build has 8 compilation errors when trying to build this version. What software are you using to compile this project?

**Comment by White-Tiger** [comment]
eh... yeah you would have to build it yourself..
Travis CI and AppVeyor are only supposed to build the final release (all any commit I tag as such)

I didn't want them to waste storage :P (or Github in that matter)
Do you consider it useful to have "live" builds there?

Anyway, I've fixed those build "errors" now..
I'm currently using GCC to do my local builds.
Reason why I've started to develop T-Clock with GCC was mainly to make sure it's properly working there... it originally didn't and still crashed after I got it to compile... So I wanted to fully test if everything is working now and there aren't any more errors. (as sad as it is.. using both GCC and MSVC reveals more bugs than using just one..)
But back when I started to work with C/C++, I did use MSVC.. just couldn't really use it for long as I also tried to write cross-platform code which almost made me rewrite my source simply because MSVC didn't follow standards... So GCC was way easier to use for such purpose. I also had the feeling that just having Visual Studio installed messed up my system.

**Comment by bilago** [comment]
Latest version compiles successfully on MSVC 2013, and the calendar now opens properly! Thanks :)

**Comment by White-Tiger** [comment]
new [pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc) which includes this fix.

Though it isn't yet including the multilingual changes required to fully support the new calendar.
