### ISSUE TITLE
Windows 10 graphical look

### ISSUE THREAD

**Issue by HenriKorhola** [White-Tiger/T-Clock#61]
Could it be possible to make the calendar have a bit more of the Windows 10 default calendar look? Now it looks a bit Windows XPish.

**Comment by White-Tiger** [comment]
no, the Win10 calendar is entirely made from scratch and HTMLish, there's no way to reuse any of it.
Besides, it wouldn't be what the in-build calendar was all about.

**Comment by HenriKorhola** [comment]
Ok, the color changers are okay in the tool but styling option (or better looking default style) for the previous/next buttons would be appreciated. The month color also adjusts the color of the week numbers making it hard to find a good looking combination of colors:
![2016-09-05_11-48-28](https://cloud.githubusercontent.com/assets/4116332/18242379/b166f83a-735e-11e6-8d9d-27c5b3ac31e0.png)
Could you make a separate color setting for the week number letters?

**Comment by White-Tiger** [comment]
I'm sorry.. but those are all the color settings that Windows offers...
The only way to got get more customizations and control about it, is to write a custom calendar from scratch _(or hook deeply into the Windows one and hope it'll do it)_

And I'm neither in the mood, nor interested into writing my own calendar as T-Clock is all about the clock. And I'll bet there are other and better calendar apps out there
