### ISSUE TITLE
[Feature request]: Allow Esc to close Calendar

### ISSUE THREAD

**Issue by pkundrat** [White-Tiger/T-Clock#62]
T-Clock calendar is a great way to show calendar week numbers, but there is no quick way to close it.
Mouse works, Alt-F4 works too - but Esc is way faster than either of those and is also natural key for this.
I would do the fix myself, but setting up the whole environment and getting to know the code structure would take couple of days, so i am just hoping current developers could implement this in couple of minutes.

**Comment by stdedos** [comment]
I feel the could be an option to make it act like the Windows Calendar too: If you click anywhere outside of the calendar, it just dies

**Comment by White-Tiger** [comment]
> If you click anywhere outside of the calendar, it just dies
that's already there... called: Close calendar on lose focus

**Comment by pkundrat** [comment]
Thanks - thats helpful, but not exactly as useful. It is sufficient for
quick looks into the calendar.
But if you want to see the calendar while working with some other program -
you dont want to close on lost focus.
So i believe Esc still makes sense (and is much faster than mouse).
I wouldnt rate is as important, only cosmetic- having Esc is also valuable
from UI consistency POV - Esc to close is quite common for transient popups
(similar to X button).
You could live without X button too, but you would miss it.

**Comment by White-Tiger** [comment]
I never said anything about not adding it :P In fact, it's working in my local version....

**Comment by pkundrat** [comment]
Haha - got me there :) Thumbs up :)

**Comment by White-Tiger** [comment]
sorry... it took a while before I've released it, but here you go ;)
[v2.4.3](//github.com/White-Tiger/T-Clock/releases/tag/v2.4.3%23471-beta)
