### ISSUE TITLE
Skip version does not work

### ISSUE THREAD

**Issue by cyrilh** [White-Tiger/T-Clock#63]
Hi,

First of all thank you for the great work.

**Context:**
I am running "v2.4.1#419-beta"
I am offered to upgrade to "Beta: v2.4.2#445", which I don't want to bother to install.
I have clicked "Regularly check for update" and "include beta versions" (which is grayed out and mandatory)

**Problem**
I click on "Skip version" but get proposed the new version approximately every day.

Thanks,
Enjoy,
Cyril

**Comment by White-Tiger** [comment]
hmm... ok that shouldn't happen.. I'll test it again to see what's wrong^^ (it used to work when I've implemented it :P)

**Comment by White-Tiger** [comment]
You don't know how right you are xD
> "include beta versions" (which is grayed out and mandatory)

exactly this is the issue.. it wasn't build into my initial update check implementation... And adding it broke the version skip... See commit ac9d8f7 _(so "skip version" was working for exactly 3 days, good job.. xD)_
Will be fixed soon, thanks a lot for reporting!

**Comment by cyrilh** [comment]
keep doing good work !

**Comment by cbcoutinho** [comment]
I have this same issue, and instead of creating a new one I'll just bandwagon onto this issue. I don't want to use the beta version - right now I'm using 2.4.0 build 384. Is it possible to un-grey-out the 'skip beta version updates' option?

Thanks for a really amazing clock application, this is great stuff

**Comment by White-Tiger** [comment]
[v2.4.3](//github.com/White-Tiger/T-Clock/releases/tag/v2.4.3%23471-beta) got it working again ;)
