### ISSUE TITLE
Does t-clock (built-in) calendar work with Win10 Anniversary 

### ISSUE THREAD

**Issue by b432291** [White-Tiger/T-Clock#68]
They just today pushed win10 Anniversary which broke t-clock. Got new version and t-clock works again, but t-clock calendar (the one from tclock) does not seem to work anymore, should it on 2.4.2.459?

**Comment by White-Tiger** [comment]
can you elaborate: “does not seem to work anymore” ?
It's working here just fine.

**Comment by b432291** [comment]
My issue, calendar works find. 1st install did not go OK I guess.
