### ISSUE TITLE
Minor calendar bug

### ISSUE THREAD

**Issue by bugmenot30701** [White-Tiger/T-Clock#69]
When I open the Calendar (6-month view), the Up and Down arrow keys on the keyboard work fine, moving me forward or backward 1 week on the calendar.  When I change focus to another window, then put focus back on the TClock Calendar, the Up and Down arrow keys no longer work.

I am using Windows 7 and the 64-bit version of TClock.

Thanks for a great product!

**Comment by White-Tiger** [comment]
is this still the case with [v2.4.3](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.3%23471-beta)?

**Comment by bugmenot30701** [comment]
Yep, still a problem in v2.4.3.

**Comment by White-Tiger** [comment]
Should be fixed in [v2.4.4](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc)
