### ISSUE TITLE
Multi-Monitor Issue

### ISSUE THREAD

**Issue by jvconroy** [White-Tiger/T-Clock#7]
OS: Windows 10
Monitor Count: 3
Version: T-Clock Redux x64 - 2.3.2 build 151

The option for "Duplicate clock on each additional task bar" for Windows 8+ is not working as expected. I have 3 monitors and it does duplicate itself on two of the three I have, but not all three. The clock is always on the main monitor. Also, the clock sometimes changes location between the 2nd and 3rd monitors (i.e. the location is not consistent).

**Comment by White-Tiger** [comment]
so... seems like I was right to assume that it only works with 2 monitors xD
I've seen that by looking though the code but didn't test it yet. Thanks for your report.

**Comment by jvconroy** [comment]
Thanks man. I also noticed that on the duplicate that is showing, the time seems to freeze and not update. I can "Refresh" it but it stays frozen.

Let me know if you need a beta tester. I'd be happy to help.

**Comment by White-Tiger** [comment]
so... the main clock works but the duplicate freezes? That's odd... they're meant to update at the same time. How often does that happen and when?
How about loosing and gaining focus on the duplicate, does that refresh it?

**Comment by jvconroy** [comment]
Yes, that is the behavior - main clock works and duplicate freezes. It is pretty consistent in that it freezes from the moment T-Clock starts, or I refresh it (I just hadn't noticed before). Losing or gaining focus does not have any affect on the frozen duplicate clock.

**Comment by White-Tiger** [comment]
solved in [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc)

**Comment by jvconroy** [comment]
Looking good. Thanks very much.
