### ISSUE TITLE
Windows 10 nothing happens if left or right click

### ISSUE THREAD

**Issue by ghost** [White-Tiger/T-Clock#70]
Just upgraded my Windows 10 to the Anniversary update and my T-Clock_static does nothing if or when I left OR right click on the clock in the taskbar. I have to always go to RUN > "C:\Program Files\T-Clock_static\Clock.exe" /PROP in order to access the context. Even adding HOT Keys does not help or work. Been at this for over 7 hours now and I'm at the end. Any suggestions?

**Comment by White-Tiger** [comment]
were you by any chance using a 32bit Windows?
if so, [v2.4.3](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.3%23471-beta) might have fixed that
