### ISSUE TITLE
Update Dialog shows wrong version to update to:

### ISSUE THREAD

**Issue by stdedos** [White-Tiger/T-Clock#76]
![image](https://cloud.githubusercontent.com/assets/133706/20246483/415a0418-a9c0-11e6-8e58-6833b36760a8.png)

**Comment by White-Tiger** [comment]
the latest version wasn't supposed to annoy users with just another update dialog.
That's why the updater wasn't allowed to "see" it. But it's working as intended ;)

There weren't that many "important" changes either, and users who did have an issue, were still able to get it ;)
