### ISSUE TITLE
How to enable Tclock portable mode?

### ISSUE THREAD

**Issue by carlos-cadu** [White-Tiger/T-Clock#77]
Hi,
I downloaded the ZIP pack and ran TClock.
However there isn't .ini file. 
When I ran TClock from another user account all settings were gone.
I would like to make it portable, in order any user account or computer would run TClock with my custom settings.
How to enable Tclock portable mode? How to enable the .ini file?
Thanks,
Carlos

**Comment by White-Tiger** [comment]
either create `T-Clock.ini` or execute the reset/creation script `.reset_portable.cmd`
