### ISSUE TITLE
T-Clock options window has an empty icon in the taskbar

### ISSUE THREAD

**Issue by ygoe** [White-Tiger/T-Clock#85]
The T-Clock options window is listed as a regular window in the Windows taskbar, but has no icon. That area is all empty. The window title bar itself does have an icon, though, as does the update check window in both title bar and taskbar.

T-Clock 2.4.2 on Windows 10.1607

**Comment by White-Tiger** [comment]
what color does your taskbar have?

**Comment by ygoe** [comment]
It's dark, but not black. No icon can be seen in all four states: inactive (dark), hovered (a bit lighter), active (darkblue), active hovered (lighter blue)

**Comment by White-Tiger** [comment]
is this issue still valid? Could you provide a screen shot?

**Comment by ygoe** [comment]
Doesn't seem to be the case with 2.4.3. There's a clock icon clearly visible in the task bar for the Options window.

**Comment by White-Tiger** [comment]
hmm... I don't know what changed though... well, I'll close it for now.
