### ISSUE TITLE
[Feature Request]: Ability to Have Date To The Right of the Time

### ISSUE THREAD

**Issue by Modelmat** [White-Tiger/T-Clock#86]
I came to use this so I can have the date on small taskbar. However, this makes the text rather small. 
An idea, is to rather than stacking them on top of each other (like in normal taskbar), can we have the option to have it to the right; eg.:
12:53:23, 15/05/16
instead of
12:53:23
15/05/16

**Comment by White-Tiger** [comment]
this is what the "New line" checkbox does... and an advanced clock format could do the same.

**Comment by Modelmat** [comment]
Well am I blind!
I searched the menus yesterday and couldn't see anything, and it took me 10 minutes to find it today.

Thanks Anyway
