### ISSUE TITLE
Taskbar items to the right of TC are moved when WM_SYSCOLORCHANGE is sent to the tray

### ISSUE THREAD

**Issue by qwerty12** [White-Tiger/T-Clock#87]
Hi,

I don't know if this is an issue peculiar to my system (Windows 10 64-bit 1607 / 14393.726) but I can reproduce the following bug with T-Clock x64 2.4.2 b. 459 (dynamically linked) every single time. Save for T-Clock, no taskbar enhancements are running (7+ Taskbar Tweaker was closed and explorer.exe killed and restarted).

If WM_SYSCOLORCHANGE is sent to the tray window, the Action Centre and show desktop icons are pushed to the right each time until, eventually, they go off screen. 
I can see this when:

* I change Windows theme
* call `SetUserColorPreference` to workaround a Windows bug that messes up my accent colour when Windows changes the active desktop to WinSta0\Winlogon 

(the WM_DWMCOLORIZATIONCOLORCHANGED case falls through to the code handling WM_SYSCOLORCHANGE ) 

and if I send WM_SYSCOLORCHANGE myself with AutoHotkey:

```
#NoEnv
#NoTrayIcon ; Showing the tray icon actually fixes this bug for one occurrence...

msg := 0x0015
PostMessage, %msg%, 0, 0,, ahk_class Shell_TrayWnd
```

My taskbar is on the top of the screen, but the same happens if I place it at the bottom

**Comment by White-Tiger** [comment]
yeah... this was known to me before though I didn't inspect it that much _(I know it'll happen on some screen-locking conditions though a theme change is fine as long as the theme actually changed)_
This happens since I had to use some messy workarounds to get T-Clock working on Windows 10 since the Anniversary update removed any interaction between the clock and the taskbar.. And this issue isn't easy to fix _(if at all possible without lots of if/then)_

All I can say now is that I'll investigate it at some time.. but that might take months and might not result in a "fix" by that time. Though, feel free to improve my code ;)

**Comment by qwerty12** [comment]
I can live with working around the bug, then (I'm sending some T-Clock specific messages once the active desktop switches back to WinSta0\Default) - I understand it was a rather large undertaking for you to actually get T-Clock running in the AU, so thank you for a T-Clock that works really well with the AU regardless!

> Though, feel free to improve my code ;)

I wish I could, but I'm nowhere near as skilled with the WinAPI as you... I have modified T-Clock for personal use, but I just ended up introducing bugs

**Comment by White-Tiger** [comment]
> I have modified T-Clock for personal use, but I just ended up introducing bugs

you may comment on what you've tried to change and what kind of bugs occured... I tried to make T-Clock easier to maintain by at least providing comments such as how defines should look like and are used.
Your "issue" suggests there's still need for improvements ;)

**Comment by qwerty12** [comment]
It was something silly for personal use - making T-Clock place one of its additional multimonitor clocks onto the primary monitor's toolbar, right in the middle of it for a GNOME-esque look. T-Clock is already really customisable enough, I just needed something a bit different and ended up making a mess of it... 

I went back to the standard T-Clock Redux builds recently (which is why I actually noticed this bug - I don't remember seeing the Action Centre being pushed off the screen with my really bad hacks to have another clock in the center of the screen and the T-Clock settings changed to push the main clock offscreen)

**Comment by MojammelW** [comment]
Hey faheem it's Mojammel 
It's been a long time. Just typed your name into Google to see if I could find you on Facebook. But I found you here. Whatsapp me please 07975559514

**Comment by White-Tiger** [comment]
Now implemented in [v2.4.4](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc)

**Comment by qwerty12** [comment]
Thank you!

**Comment by White-Tiger** [comment]
Off topic: was that post by MojammelW spam or did you actually know him?
Anyway, should I remove it? / did you get his phone number so that I can eradicate that one?

**Comment by qwerty12** [comment]
I did know him once upon a time... I'm sorry he commented on this bug - you should remove that comment
