### ISSUE TITLE
T-Clock doesn't refresh tray clock with Advanced clock format

### ISSUE THREAD

**Issue by b72i** [White-Tiger/T-Clock#92]
Windows 7 x64
With Basic clock confirugation works, but with Advanced clock format doesn't refresh the clock.

**Comment by White-Tiger** [comment]
it should... sooner or later^^ what's your format?

**Comment by b72i** [comment]
HH:mm  yyyy.mm.dd ddd

**Comment by White-Tiger** [comment]
Well... why do you need the 2 digit month format twice? And in such an awkward position next to hours?

**Comment by b72i** [comment]
Sorry, it was my mistake!!!
Wit this format works fine: HH:nn yyyy.mm.dd ddd
